weight = int(input("Weight: "))
unit = input("(K)g or (L)bs: ")
if unit = k or K:
  weight_in_pounds = weight * 2.20462
  print("Weight in lbs: " + weight_in_pounds)
else:
  weight_in_kilos = weight * 0.453592
  print("Weight in Kg: " + weight_in_kilos)
